name: Claymore
version: 0.0.1
description: Simple Mustache Render Framework
author: Faisal Abid faisal.abid@gmail.com
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  mustache4dart: '>= 1.0.0 < 2.0.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
